#!/bin/bash

export wwwtests=/home/chrissy/git/splunge/tests/www
export src=/home/chrissy/git/splunge/src
parallel 'ln -sf {} $src/$(basename {})' ::: $(find $wwwtests -mindepth 1 -maxdepth 1 -type d -print)
