[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "splunge"
version = "0.1.1"
dependencies = [
    "gunicorn",
    "jinja2",
    "markdown-it-py",
	"toml",
    "pygments",
    "werkzeug",
]

[project.scripts]
splunge = "splunge.cli:main"

[tool.setuptools]
script-files = ["scripts/www"]

[tool.setuptools.packages.find]
where = ["src"]
