#!/usr/bin/env bash
set -eu
target=${1:?usage: $0 <target-dir>}

mkdir -p "$target/Indianapolis_Racers"
mkdir -p "$target/Indianapolis_Racers/Jaxson"
mkdir -p "$target/Scarolina_Panzers"
touch "$target/Indianapolis_Racers/Jaxson/crystal.py"
printf "%s\n" 'name = '"'"'crystal-san'"'"'' >> "$target/Indianapolis_Racers/Jaxson/crystal.py"
touch "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'from .. import rel1' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'from ...Scarolina_Panzers import rel2' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'from . import rel3' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'from . import rel4' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'import bullwinkle' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'import Scarolina_Panzers.rufus' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'import Indianapolis_Racers.latte' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'import Indianapolis_Racers.Jaxson.crystal' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
printf "%s\n" 'name = '"'"'hello3-san'"'"'' >> "$target/Indianapolis_Racers/Jaxson/hello3.py"
touch "$target/Indianapolis_Racers/Jaxson/rel4.py"
printf "%s\n" 'from .. import rel1' >> "$target/Indianapolis_Racers/Jaxson/rel4.py"
printf "%s\n" 'import Indianapolis_Racers.Jaxson.crystal' >> "$target/Indianapolis_Racers/Jaxson/rel4.py"
printf "%s\n" 'name = '"'"'rel4-san'"'"'' >> "$target/Indianapolis_Racers/Jaxson/rel4.py"
touch "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'from . import rel1' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'from ..Scarolina_Panzers import rel2' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'from . import rel3' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'from .Jaxson import rel4' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'import bullwinkle' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'import Scarolina_Panzers.rufus' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'import Indianapolis_Racers.latte' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'import Indianapolis_Racers.Jaxson.crystal' >> "$target/Indianapolis_Racers/hello2.py"
printf "%s\n" 'name = '"'"'hello2-san'"'"'' >> "$target/Indianapolis_Racers/hello2.py"
touch "$target/Indianapolis_Racers/latte.py"
printf "%s\n" 'name = '"'"'latte-san'"'"'' >> "$target/Indianapolis_Racers/latte.py"
touch "$target/Indianapolis_Racers/rel3.py"
printf "%s\n" 'from . import rel1' >> "$target/Indianapolis_Racers/rel3.py"
printf "%s\n" 'import Scarolina_Panzers.rufus' >> "$target/Indianapolis_Racers/rel3.py"
printf "%s\n" 'import bullwinkle' >> "$target/Indianapolis_Racers/rel3.py"
printf "%s\n" 'name = '"'"'rel3-san'"'"'' >> "$target/Indianapolis_Racers/rel3.py"
touch "$target/Scarolina_Panzers/rel2.py"
printf "%s\n" 'from ..Indianapolis_Racers import rel3' >> "$target/Scarolina_Panzers/rel2.py"
printf "%s\n" 'import Indianapolis_Racers.latte' >> "$target/Scarolina_Panzers/rel2.py"
printf "%s\n" 'name = '"'"'rel2-san'"'"'' >> "$target/Scarolina_Panzers/rel2.py"
touch "$target/Scarolina_Panzers/rufus.py"
printf "%s\n" 'name = '"'"'rufus-san'"'"'' >> "$target/Scarolina_Panzers/rufus.py"
touch "$target/bullwinkle.py"
printf "%s\n" 'import Indianapolis_Racers.latte' >> "$target/bullwinkle.py"
printf "%s\n" 'name = '"'"'bullwinkle-san'"'"'' >> "$target/bullwinkle.py"
touch "$target/hello1.py"
printf "%s\n" 'from . import rel1' >> "$target/hello1.py"
printf "%s\n" 'from .Scarolina_Panzers import rel2' >> "$target/hello1.py"
printf "%s\n" 'from .Indianapolis_Racers import rel3' >> "$target/hello1.py"
printf "%s\n" 'from .Indianapolis_Racers.Jaxson import rel4' >> "$target/hello1.py"
printf "%s\n" 'import bullwinkle' >> "$target/hello1.py"
printf "%s\n" 'import Scarolina_Panzers.rufus' >> "$target/hello1.py"
printf "%s\n" 'import Indianapolis_Racers.latte' >> "$target/hello1.py"
printf "%s\n" 'import Indianapolis_Racers.Jaxson.crystal' >> "$target/hello1.py"
printf "%s\n" 'name = '"'"'hello1-san'"'"'' >> "$target/hello1.py"
touch "$target/rel1.py"
printf "%s\n" 'name = '"'"'rel1-san'"'"'' >> "$target/rel1.py"
