[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mess"
version = "0.0.1"
dependencies = [
	"bs4",
	"lxml",
	"splunge @ file:///home/chris.linux/projects/daylight/src/splunge"
]

[project.scripts]
brap = 'brap:main'
write_table = 'syscalls:write_syscall_table'

[tool.setuptools]
py-modules = ['messaround', 'boxylady', 'brap', 'syscalls', 'libc']
script-files = ["./messaround"]

[project.optional-dependencies]
# dev = []

[project.urls]
# repository = "https://github.com/..."
# documentation = "https://..."

# [tool.setuptools.packages.find]
# where = ["."]

[tool.pytest.ini_options]
# testpaths = ["."]
# markers   = ["slow: marks tests as slow"]
# addopts   = "--tb=short --strict-markers"
