#! /usr/bin/env python

import sys

if __name__ == '__main__':
    for mpf in sys.meta_path:
        spec = mpf.find_spec('mycode.foo', 'mycode/foo')
        if spec:
            print(mpf)
            print(spec)
        else:
            print(f"spec not found (mpf={mpf})")