#!/usr/bin/env bash -x

DEFAULT_PORT=1313
port=${1:-$DEFAULT_PORT}
logFolder="$HOME/tmp/splunge/log"
mkdir -p "$logFolder/" || { printf 'Unable to create log folder %s\n' "$logFolder" &>2; return; }
echo "Running splunge on port $port & logging to $logFolder ..."


gunicorn --bind localhost:$port \
         --access-logfile "$logFolder/access.log" \
         --error-logfile "$logFolder/errors.log" \
         --workers 3 \
         --umask 007 \
         --reload \
         splunge.app:app \
         || cat "$logFolder/errors.log"