#!/usr/bin/env bash

DEFAULT_PORT=1313

port=${1:-$DEFAULT_PORT}
echo "\$port=$port"
echo Running splunge on port $port... 
# gunicorn -b localhost:$port splunge.App:Application
gunicorn --bind localhost:$port \
         --access-logfile /tmp/splunge/log/access.log \
         --error-logfile /tmp/splunge/log/errors.log \
         --workers 3 \
         --umask 007 \
         --reload \
         splunge.App2:application